version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        columns: 
          - name: date_date
            description: date of purchase
            tests:
              - not_null
          - name: orders_id
            description: Unique ID for each order
            tests:
              - not_null
          - name: products_id
            description: a unique ID for each product
          - name: revenue
            description: total amount of revenue generated per order
          - name: quantity
            description: quantity of products purchased

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / we have one row per product_id and their price
        columns:
          - name: products_id
            description: a unique identifier per product
            tests:
              - not_null
          - name: purchase_price
            description: price for each product

      - name: ship
        identifier: raw_gz_ship
        description: shippings of Greenweez / we have one row per order shipped
        columns:
          - name: orders_id
            description: a unique ID for each order
            tests:
              - not_null
              - unique
          - name: shipping_fee
            description: cost of shipping per order
          - name: logcost
            description: price of log
          - name: ship_cost
            description: amount spent for the shipping

      - name: adwords
        identifier: raw_gz_adwords
        description: Adwords marketing campaigns
        columns: 
          - name: date_date
          - name: paid_source
          - name: campaign_key
            tests:
              - not_null
          - name: campaign_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "date_date || campaign_key"
      - name: bing
        identifier: raw_gz_bing
        description: Bing marketing campaigns
        columns: 
          - name: date_date
          - name: paid_source
          - name: campaign_key
            tests:
              - not_null
          - name: campaign_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "date_date || campaign_key"
      - name: criteo
        identifier: raw_gz_criteo
        description: Criteo marketing campaigns
        columns: 
          - name: date_date
          - name: paid_source
          - name: campaign_key
            tests:
              - not_null
          - name: campaign_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "date_date || campaign_key"
      - name: facebook
        identifier: raw_gz_facebook
        description: Facebook marketing campaigns
        columns: 
          - name: date_date
          - name: paid_channel
          - name: campaign_key
            tests:
              - not_null
          - name: campaign_name
          - name: ads_cost
          - name: impression
          - name: click
        tests:
          - unique:
              column_name: "date_date || campaign_key"
