version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        columns: 
            - name: date_date
              tests:
                - not_null
              description: date of purchase
            - name: orders_id
              tests:
                - not_null
              description: Unique ID for each order
            - name: products_id
              description: a unique ID for each product
            - name: revenue
              description: total amount of revenue generated per order
            - name: quantity
              description: quantity of products purchased
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / we have one row per product_id and their price
        columns:
          - name: products_id
            tests:
              - not_null
            description: a unique identifier per product
          - name: purchase_price
            description: price for each product
      - name: ship
        identifier: raw_gz_ship
        description: shippings of Greenweez / we have one row per order shipped
        columns:
          - name: orders_id
            tests:
              - not_null
              - unique
            description: a unique ID for each order
          - name: shipping_fee
            description: cost of shipping per order
          - name: logcost
            description: price of log
          - name: ship_cost
            description: amount spent for the shipping
    